#!/bin/bash

## Takes the name of the robot as a single argument (ex. "./generate_dar_from_urdf.sh darci")

#Generate URDF from Xacro files
rosrun xacro xacro.py ./robots/asus_base.urdf.xacro > ./robots/asus_base.urdf

#Convert URDF to SDF
gzsdf print ./robots/asus_base.urdf > sdf/generated_model.sdf

#Fix Links as generated by the gzsdf command
sed -i "s/asus_description\/urdf/asus_base/g" sdf/generated_model.sdf
